Feb 03 17:09:32 pldevlvault1.test.net agent[3777076]: 2025-02-03 17:09:32 CST | CORE | ERROR | (pkg/collector/worker/check_logger.go:71 in Error) | check:vault | Error running check: [{"message":"There was an error scraping endpoint http://localhost:8200/v1/sys/metrics?format=prometheus: 403 Client Error: Forbidden for url: http://localhost:8200/v1/sys/metrics?format=prometheus","traceback":"Traceback (most recent call last):\n  File \"/opt/datadog-agent/embedded/lib/python3.12/site-packages/datadog_checks/base/checks/base.py\", line 1301, in run\n    self.check(instance)\n  File \"/opt/datadog-agent/embedded/lib/python3.12/site-packages/datadog_checks/vault/check.py\", line 74, in check\n    super().check(_)\n  File \"/opt/datadog-agent/embedded/lib/python3.12/site-packages/datadog_checks/base/checks/openmetrics/v2/base.py\", line 75, in check\n    raise type(e)(\"There was an error scraping endpoint {}: {}\".format(endpoint, e)) from None\nrequests.exceptions.HTTPError: There was an error scraping endpoint http://localhost:8200/v1/sys/metrics?format=prometheus: 403 Client Error: Forbidden for url: http://localhost:8200/v1/sys/metrics?format=prometheus\n"}]
